### PR TITLE
Adding ToggleState property to ToggleButton class

### PR DESCRIPTION
**Pull request by HyruleWarrior**
Adding ToggleState property to ToggleButton class. My only thought/concern now is that ToggleButton inherits from ToggleAutomationElement instead of Button. I am not sure how much this matters, but a ToggleButton won't have the InvokePattern. When I first created a ToggleButton class, I just inherited from Button and then added the needed stuff for implementing the Toggle Pattern in that class.

### CODE REVIEW

**Comment by Roemer** [comment]
I renamed the ToggleState directly on the base element.
I also added a IsToggled boolean and also an IsChecked boolean to CheckBox.
See Commit https://github.com/Roemer/FlaUI/commit/12d4dfada918485e9acc0ce6de00d631f31d9f87
This should superseed this PR. Do you agree?

**Comment by HyruleWarrior** [comment]
Yeah that looks good to me. What are your thoughts on ToggleButton not having the InvokePattern? I haven't used that much so I don't know if it is an issue, but I could see it maybe being an issue if someone expects ToggleButton to inherit from Button. This probably isn't the place for that discussion anyways, just a thought.

**Comment by Roemer** [comment]
All toggle buttons I know do not support the invoke pattern. Have you seen one that supports it?

**Comment by HyruleWarrior** [comment]
Yeah, I think you are right. I have not seen one either and it doesn't really make sense to have a toggle button support the Invoke Pattern.

**Comment by Roemer** [comment]
PR superseeded with commit https://github.com/Roemer/FlaUI/commit/12d4dfada918485e9acc0ce6de00d631f31d9f87

**Pull request closed without merging**
