### PR TITLE
corrected target framework tag

### PR DESCRIPTION
**Pull request by RomanKalachik**
MSBuild15 does not work with this <TargetFrameworks>net35;net40;net45</TargetFrameworks>

### CODE REVIEW

**Comment by Roemer** [comment]
This is only related the core msbuild right?

**Comment by Roemer** [comment]
If possible, I want to keep .net 3.5 support so it can be used with thinks like PowerShell 2.0

**Comment by Roemer** [comment]
According to https://github.com/Microsoft/msbuild/issues/1333 there is a possible workaround:
```xml
<PropertyGroup>
  <FrameworkPathOverride Condition="'$(TargetFramework)' == 'net35'">C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client</FrameworkPathOverride>
</PropertyGroup>
```
Can you instead try this?

**Comment by RomanKalachik** [comment]
Ok, thanks for the link. I was able to workaround this.

**Comment by Roemer** [comment]
Which exact version (installer link?) of msbuild are you using?

**Pull request closed without merging**
